### PR TITLE
DragonFly BSD support

### PR DESCRIPTION
**Pull request by apamment**
Just a minor patch to make it compile on DragonFly BSD

### CODE REVIEW

**Comment by lovell** [comment]
Hello, please can you submit the same change to the upstream [google/farmhash](https://github.com/google/farmhash/blob/b64d037e1fba0500a54f22240c843fc854954c3a/src/farmhash.cc#L141) repo first then we can sync the code.

**Comment by apamment** [comment]
ok

**Comment by lovell** [comment]
https://github.com/google/farmhash/pull/18

**Comment by lovell** [comment]
Hello, it looks there have been other upstream changes since I last synchronised so I've landed this in commit 60f9fa5c. This will be in the forthcoming v2.0.0 release. Thanks for your contribution!

**Pull request closed without merging**
