### PR TITLE
Fix build on Windows

### LINKED ISSUE #4: Build Error on Windows: '__builtin_expect' identifier not found
## Error
```
..\src\upstream\farmhash.cc(1378): error C3861: '__builtin_expect': identifier not found [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
```

## Versions
```
OS: Windows 10 Tech Preview
node 0.10.35
npm 1.4.28
node-gyp 1.0.1
```

## Output
```
C:\Users\Jonas\Code\node-hexadb>npm i --save farmhash
npm http GET https://registry.npmjs.org/farmhash
npm http 200 https://registry.npmjs.org/farmhash
npm http GET https://registry.npmjs.org/farmhash/-/farmhash-0.1.0.tgz
npm http 200 https://registry.npmjs.org/farmhash/-/farmhash-0.1.0.tgz
npm http GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-1.4.1.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-1.4.1.tgz

> farmhash@0.1.0 install C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash
> node-gyp rebuild


C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(942,5): warning MSB8027: Two or more files with the name of farmhash.cc will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are ..\src\upstream\farmhash.cc, ..\src\farmhash.cc. [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
  farmhash.cc
  farmhash.cc
..\src\upstream\farmhash.cc(407): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(481): warning C4307: '*' : integral constant overflow [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(548): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(566): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(570): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(585): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(641): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(650): warning C4267: 'return' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(873): warning C4267: 'return' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(902): warning C4267: 'return' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1128): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1141): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1145): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1160): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1227): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1277): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1316): warning C4267: 'initializing' : conversion from 'size_t' to 'long', possible loss of data [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
..\src\upstream\farmhash.cc(1378): error C3861: '__builtin_expect': identifier not found [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\src\farmhash.cc) [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
C:\Users\Jonas\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' (..\src\farmhash.cc) [C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash\build\farmhash.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jonas\Code\node-hexadb\node_modules\farmhash
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! farmhash@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the farmhash@0.1.0 install script.
npm ERR! This is most likely a problem with the farmhash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls farmhash
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "farmhash"
npm ERR! cwd C:\Users\Jonas\Code\node-hexadb
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

### PR DESCRIPTION
**Pull request by jhermsmeier**
Fixes #4 

### Renamed src/farmhash.cc -> src/bindings.cc

Two or more files with the name of farmhash.cc will produce outputs to the
same location. This can lead to an incorrect build result.
Fixes linker issues on Windows, as described in issue #4

### 	Added check for __GNUC__ in upstream/farmhash.cc

Checking if `!defined(__GNUC__)` prevents msbuild from erroring due to
`__builtin_expect` not existing. Original fix from Colin Riddell, see
https://groups.google.com/forum/#!msg/farmhash-discuss/xTkB3uv62pw/wAusRsWMeaAJ

### CODE REVIEW

**Comment by lovell** [comment]
Thanks! Did adding `-DFARMHASH_OPTIONAL_BUILTIN_EXPECT` without the `!defined(__GNUC__)` change also work?

**Comment by jhermsmeier** [comment]
Sure. Well, for some reason `-DFARMHASH_OPTIONAL_BUILTIN_EXPECT` alone has no effect whatsoever, `!defined(__GNUC__)` was necessary. I also think that checking for `__GNUC__` might be a more robust solution, there might be people with some awkward compiler contraptions on other platforms as well, no?

**Comment by lovell** [comment]
Yes, clang (and IIRC Intel's C compiler) also defines the `__GNUC__` macro so that should work.

Should the upstream code change I'll need to remember to add this again. Perhaps we could define `FARMHASH_OPTIONAL_BUILTIN_EXPECT` at the top of the renamed bindings.cc instead, something like:

```c
#if !defined(__GNUC__)
#define FARMHASH_OPTIONAL_BUILTIN_EXPECT
#endif

#include "upstream/farmhash.h"
...
```

**Comment by jhermsmeier** [comment]
What you suggested makes a whole lot more sense, but upon trying that, it just didn't work. I'm guessing that's because `msbuild` builds `bindings.cc` and the upstream code seperately.

So I just had a quick look at the gyp docs, and added `FARMHASH_OPTIONAL_BUILTIN_EXPECT` as a conditional define for Windows, which builds nicely and doesn't touch the code. Still wonder why setting `-DFARMHASH_OPTIONAL_BUILTIN_EXPECT` in the `cflags_cc` didn't work, though.

**Comment by lovell** [comment]
Perfect, that looks much more maintainable, thank you for persisting with this Jonas.

You more than deserve to add your name to the [contributers](https://github.com/lovell/farmhash/blob/master/package.json#L5) list. Are you able to add yourself then rebase against upstream/master and squash all of your fantastic work into a single commit?

**Comment by jhermsmeier** [comment]
Thanks, glad I could help! Added myself to the contributors & squashed now, should be good to go.

**Comment by lovell** [comment]
Great work, thanks again. I'll publish to npm when I get a moment over the weekend.

**Pull request merged**
